name: php-package-template
services:
  appserver:
    type: php:custom
    via: cli
    overrides:
      image: slimdeluxe/php:8.1
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
