name: Code linting

on:
  # Run linting on all push events that have committed changes in PHP files
  push:
    paths:
      - '**.php'

jobs:
  phplint:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Run Laravel Pint
      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@2.3.0

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: fix code style"
